# Generated by Django 5.1.7 on 2025-10-03 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='staff_photos/')),
                ('salutation', models.CharField(choices=[('Dr.', 'Dr.'), ('Prof.', 'Prof.'), ('Mr.', 'Mr.'), ('Ms.', 'Ms.')], max_length=10)),
                ('designation', models.CharField(max_length=100)),
                ('department', models.CharField(default='Information Technology', max_length=100)),
                ('qualification', models.CharField(max_length=255)),
                ('specialization', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('date_of_joining', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True)),
                ('academic_details', models.TextField(blank=True, help_text='List your degrees and qualifications.')),
                ('experience', models.TextField(blank=True, help_text='Describe your previous work experience.')),
                ('publications', models.TextField(blank=True, help_text='List your key publications, one per line.')),
                ('awards_and_memberships', models.TextField(blank=True, help_text='List any awards, honors, or professional memberships.')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
