# Generated by Django 5.1.7 on 2026-01-08 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0007_staffleaverequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffleaverequest',
            name='document',
            field=models.FileField(blank=True, help_text='Required for Medical Leave and On Other Duty', null=True, upload_to='leave_docs/'),
        ),
        migrations.AlterField(
            model_name='staffleaverequest',
            name='leave_type',
            field=models.CharField(choices=[('CL', 'Casual Leave (CL)'), ('Religious', 'Religious Holiday'), ('Medical', 'Medical Leave'), ('Earned', 'Earned Leave'), ('BV', 'Compensation Leave'), ('OD', 'On Other Duty'), ('Special', 'Special Casual Leave')], max_length=20),
        ),
    ]
