# Generated by Django 5.1.7 on 2026-01-08 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0008_staffleaverequest_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffleaverequest',
            name='leave_type',
            field=models.CharField(choices=[('CL', 'Casual Leave (CL)'), ('Religious', 'Religious Holiday'), ('Medical', 'Medical Leave'), ('Earned', 'Earned Leave'), ('OD', 'On Other Duty'), ('Special', 'Special Casual Leave')], max_length=20),
        ),
    ]
