# Generated by Django 5.1.7 on 2026-01-08 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0009_alter_staffleaverequest_leave_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('target', models.CharField(choices=[('All', 'All'), ('Staff', 'Staff Only'), ('Student', 'Student Only')], default='All', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'News & Announcements',
                'ordering': ['-date'],
            },
        ),
    ]
