# Generated by Django 5.1.7 on 2026-01-08 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0010_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='link',
            field=models.URLField(blank=True, help_text='Optional link to external resource', null=True),
        ),
    ]
