# Generated by Django 5.1.7 on 2026-02-02 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0019_add_audit_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Book', 'Book'), ('Popular Article', 'Popular Article')], default='Book', max_length=20)),
                ('author_name', models.CharField(max_length=255)),
                ('title_of_book', models.CharField(max_length=500)),
                ('publisher_name', models.CharField(blank=True, max_length=255)),
                ('publisher_address', models.TextField(blank=True)),
                ('isbn_issn_number', models.CharField(blank=True, max_length=100)),
                ('page_numbers_from', models.CharField(blank=True, max_length=50)),
                ('page_numbers_to', models.CharField(blank=True, max_length=50)),
                ('month_of_publication', models.CharField(blank=True, max_length=20)),
                ('year_of_publication', models.CharField(blank=True, max_length=20)),
                ('url_address', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='staffs.staff')),
            ],
        ),
        migrations.CreateModel(
            name='ConferenceParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_international', models.CharField(choices=[('National', 'National'), ('International', 'International')], default='National', max_length=20)),
                ('author_name', models.CharField(max_length=255)),
                ('year_of_publication', models.CharField(blank=True, max_length=20)),
                ('title_of_paper', models.CharField(max_length=500)),
                ('title_of_proceedings', models.CharField(blank=True, max_length=500)),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('page_numbers_from', models.CharField(blank=True, max_length=50)),
                ('page_numbers_to', models.CharField(blank=True, max_length=50)),
                ('place_of_publication', models.CharField(blank=True, max_length=255)),
                ('publisher_proceedings', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conferences', to='staffs.staff')),
            ],
        ),
        migrations.CreateModel(
            name='JournalPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_international', models.CharField(choices=[('National', 'National'), ('International', 'International')], default='National', max_length=20)),
                ('published_month', models.CharField(blank=True, max_length=20)),
                ('published_year', models.CharField(blank=True, max_length=20)),
                ('author_name', models.CharField(max_length=255)),
                ('title_of_paper', models.CharField(max_length=500)),
                ('journal_name', models.CharField(max_length=500)),
                ('volume_number', models.CharField(blank=True, max_length=50)),
                ('issue_number', models.CharField(blank=True, max_length=50)),
                ('year_of_publication_doi', models.CharField(blank=True, max_length=255)),
                ('page_numbers_from', models.CharField(blank=True, max_length=50)),
                ('page_numbers_to', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journals', to='staffs.staff')),
            ],
        ),
    ]
