# Generated by Django 5.1.7 on 2026-02-03 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0020_bookpublication_conferenceparticipation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='end_date',
            field=models.DateField(blank=True, help_text='Date when this announcement should stop showing', null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='start_date',
            field=models.DateField(blank=True, help_text='Date when this announcement should start showing', null=True),
        ),
    ]
