# Generated by Django 5.1.7 on 2026-02-04 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0021_news_end_date_news_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffawardhonour',
            name='awarded_by',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='staffseminar',
            name='date_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffseminar',
            name='date_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffstudentguided',
            name='supporting_document',
            field=models.FileField(blank=True, help_text='Memo/Provisional Certificate for PG/PhD, Allocation Order for New Students', null=True, upload_to='staff/student_docs/'),
        ),
    ]
