# Generated by Django 5.1.7 on 2026-02-04 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0022_staffawardhonour_awarded_by_staffseminar_date_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookpublication',
            name='supporting_document',
            field=models.FileField(blank=True, help_text='Upload Cover Page/Proof', null=True, upload_to='staff/book_docs/'),
        ),
        migrations.AddField(
            model_name='conferenceparticipation',
            name='supporting_document',
            field=models.FileField(blank=True, help_text='Upload Certificate/Paper', null=True, upload_to='staff/conference_docs/'),
        ),
        migrations.AddField(
            model_name='journalpublication',
            name='supporting_document',
            field=models.FileField(blank=True, help_text='Upload Paper Copy', null=True, upload_to='staff/journal_docs/'),
        ),
        migrations.AddField(
            model_name='staffawardhonour',
            name='supporting_document',
            field=models.FileField(blank=True, help_text='Upload Certificate/Letter', null=True, upload_to='staff/award_docs/'),
        ),
        migrations.AddField(
            model_name='staffseminar',
            name='supporting_document',
            field=models.FileField(blank=True, help_text='Upload Certificate', null=True, upload_to='staff/seminar_docs/'),
        ),
    ]
