# Generated by Django 5.1.7 on 2026-02-04 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0023_bookpublication_supporting_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferenceparticipation',
            name='participation_type',
            field=models.CharField(choices=[('Presented', 'Presented'), ('Attended', 'Attended')], default='Presented', max_length=20),
        ),
        migrations.AlterField(
            model_name='conferenceparticipation',
            name='author_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='conferenceparticipation',
            name='title_of_paper',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
