# Generated by Django 5.1.7 on 2026-02-06 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0024_conferenceparticipation_participation_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('HOD', 'HOD'), ('Class Incharge', 'Class Incharge'), ('Course Incharge', 'Course Incharge'), ('Scholarship Officer', 'Scholarship Officer')], default='HOD', max_length=50),
        ),
    ]
