# Generated by Django 5.1.7 on 2026-02-12 17:45

import ssm.upload_paths
import ssm.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0028_alter_bookpublication_supporting_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='document',
            field=models.FileField(blank=True, help_text='Upload a document (PDF, DOC, etc.) related to this announcement', null=True, upload_to='ssm.upload_paths.news_documents_path'),
        ),
        migrations.AddField(
            model_name='news',
            name='new_gif_end_date',
            field=models.DateField(blank=True, help_text='Date when the NEW indicator should stop showing (must not exceed news end date)', null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='new_gif_start_date',
            field=models.DateField(blank=True, help_text='Date when the NEW indicator should start showing', null=True),
        ),
        migrations.AlterField(
            model_name='bookpublication',
            name='supporting_document',
            field=models.FileField(blank=True, help_text='Upload Cover Page/Proof', null=True, upload_to=ssm.upload_paths.staff_book_document_path, validators=[ssm.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='conferenceparticipation',
            name='supporting_document',
            field=models.FileField(blank=True, help_text='Upload Certificate/Paper', null=True, upload_to=ssm.upload_paths.staff_conference_document_path, validators=[ssm.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='journalpublication',
            name='supporting_document',
            field=models.FileField(blank=True, help_text='Upload Paper Copy', null=True, upload_to=ssm.upload_paths.staff_journal_document_path, validators=[ssm.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='staff',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=ssm.upload_paths.staff_photo_path, validators=[ssm.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('HOD', 'HOD'), ('Class Incharge', 'Class Incharge'), ('Course Incharge', 'Course Incharge'), ('Scholarship Officer', 'Scholarship Officer'), ('Office Staff', 'Office Staff')], default='Course Incharge', max_length=50),
        ),
        migrations.AlterField(
            model_name='staffawardhonour',
            name='supporting_document',
            field=models.FileField(blank=True, help_text='Upload Certificate/Letter', null=True, upload_to=ssm.upload_paths.staff_award_document_path, validators=[ssm.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='staffleaverequest',
            name='document',
            field=models.FileField(blank=True, help_text='Required for Medical Leave and On Other Duty', null=True, upload_to=ssm.upload_paths.staff_leave_document_path, validators=[ssm.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='staffseminar',
            name='supporting_document',
            field=models.FileField(blank=True, help_text='Upload Certificate', null=True, upload_to=ssm.upload_paths.staff_seminar_document_path, validators=[ssm.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='staffstudentguided',
            name='supporting_document',
            field=models.FileField(blank=True, help_text='Memo/Provisional Certificate for PG/PhD, Allocation Order for New Students', null=True, upload_to=ssm.upload_paths.staff_student_guided_document_path, validators=[ssm.validators.validate_file_size]),
        ),
    ]
