# Generated by Django 5.1.7 on 2026-03-01 16:22

import django.db.models.deletion
import ssm.upload_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0029_news_document_news_new_gif_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='document',
            field=models.FileField(blank=True, help_text='Upload a document (PDF, DOC, etc.) related to this announcement', null=True, upload_to=ssm.upload_paths.news_documents_path),
        ),
        migrations.CreateModel(
            name='ClassSubstitutionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('period', models.IntegerField(help_text='1 to 7')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('leave_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staffs.staffleaverequest')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitution_requests_made', to='staffs.staff')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staffs.subject')),
                ('substitute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitution_requests_received', to='staffs.staff')),
            ],
            options={
                'ordering': ['-date', 'period'],
                'unique_together': {('requester', 'date', 'period')},
            },
        ),
    ]
