# Generated by Django 5.1.7 on 2026-03-25 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0030_alter_news_document_classsubstitutionrequest'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='timetable',
            name='batch',
            field=models.CharField(choices=[('All', 'All'), ('A', 'Batch A'), ('B', 'Batch B')], default='All', max_length=3),
        ),
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together={('semester', 'day', 'period', 'batch')},
        ),
    ]
