# Generated by Django 5.1.7 on 2026-04-05 17:57

import django.db.models.deletion
import ssm.upload_paths
import ssm.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0031_alter_timetable_unique_together_timetable_batch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='initial',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='staff',
            name='is_profile_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='StaffMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute_name', models.CharField(max_length=255)),
                ('membership_no', models.CharField(max_length=100)),
                ('membership_type', models.CharField(max_length=100)),
                ('year', models.CharField(blank=True, max_length=10)),
                ('month', models.CharField(blank=True, max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='staffs.staff')),
            ],
            options={
                'ordering': ['-year', '-order', 'institute_name'],
            },
        ),
        migrations.CreateModel(
            name='StaffPastDesignation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=100)),
                ('from_date', models.DateField(blank=True, null=True)),
                ('to_date', models.DateField(blank=True, null=True)),
                ('order_img', models.FileField(blank=True, help_text='Upload Order Document', null=True, upload_to=ssm.upload_paths.staff_designation_document_path, validators=[ssm.validators.validate_file_size])),
                ('order', models.PositiveIntegerField(default=0)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='past_designations', to='staffs.staff')),
            ],
            options={
                'ordering': ['-from_date', '-order', 'designation'],
            },
        ),
        migrations.CreateModel(
            name='StaffQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=100)),
                ('university', models.CharField(max_length=255)),
                ('year_completed', models.CharField(max_length=10)),
                ('certificate', models.FileField(blank=True, help_text='Upload Certificate', null=True, upload_to=ssm.upload_paths.staff_qualification_document_path, validators=[ssm.validators.validate_file_size])),
                ('order', models.PositiveIntegerField(default=0)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='staffs.staff')),
            ],
            options={
                'ordering': ['-year_completed', '-order', 'degree'],
            },
        ),
    ]
