# Generated by Django 5.1.7 on 2026-04-07 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0032_staff_initial_staff_is_profile_complete_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffGenerator',
            fields=[
            ],
            options={
                'verbose_name': 'Generate Staff',
                'verbose_name_plural': 'Generate Staff',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('staffs.staff',),
        ),
    ]
