# Generated by Django 5.1.7 on 2026-04-21 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0034_alter_staff_email'),
        ('students', '0043_add_pending_guide_leave_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookpublication',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scholar_books', to='students.student'),
        ),
        migrations.AddField(
            model_name='conferenceparticipation',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scholar_conferences', to='students.student'),
        ),
        migrations.AddField(
            model_name='journalpublication',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scholar_journals', to='students.student'),
        ),
        migrations.AddField(
            model_name='staffawardhonour',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scholar_awards', to='students.student'),
        ),
        migrations.AddField(
            model_name='staffseminar',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scholar_seminars', to='students.student'),
        ),
    ]
