# Generated by Django 5.1.7 on 2026-04-21 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0035_bookpublication_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookpublication',
            name='associated_staffs',
            field=models.ManyToManyField(blank=True, related_name='associated_books', to='staffs.staff'),
        ),
        migrations.AddField(
            model_name='conferenceparticipation',
            name='associated_staffs',
            field=models.ManyToManyField(blank=True, related_name='associated_conferences', to='staffs.staff'),
        ),
        migrations.AddField(
            model_name='journalpublication',
            name='associated_staffs',
            field=models.ManyToManyField(blank=True, related_name='associated_journals', to='staffs.staff'),
        ),
        migrations.AddField(
            model_name='staffawardhonour',
            name='associated_staffs',
            field=models.ManyToManyField(blank=True, related_name='associated_awards', to='staffs.staff'),
        ),
        migrations.AddField(
            model_name='staffseminar',
            name='associated_staffs',
            field=models.ManyToManyField(blank=True, related_name='associated_seminars', to='staffs.staff'),
        ),
    ]
