# Generated by Django 5.1.7 on 2026-04-21 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0036_bookpublication_associated_staffs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookpublication',
            name='associated_staffs',
        ),
        migrations.RemoveField(
            model_name='conferenceparticipation',
            name='associated_staffs',
        ),
        migrations.RemoveField(
            model_name='journalpublication',
            name='associated_staffs',
        ),
        migrations.RemoveField(
            model_name='staffawardhonour',
            name='associated_staffs',
        ),
        migrations.RemoveField(
            model_name='staffseminar',
            name='associated_staffs',
        ),
        migrations.RemoveField(
            model_name='bookpublication',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='conferenceparticipation',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='journalpublication',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='staffawardhonour',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='staffseminar',
            name='staff',
        ),
        migrations.AddField(
            model_name='bookpublication',
            name='staff',
            field=models.ManyToManyField(blank=True, related_name='books', to='staffs.staff'),
        ),
        migrations.AddField(
            model_name='conferenceparticipation',
            name='staff',
            field=models.ManyToManyField(blank=True, related_name='conferences', to='staffs.staff'),
        ),
        migrations.AddField(
            model_name='journalpublication',
            name='staff',
            field=models.ManyToManyField(blank=True, related_name='journals', to='staffs.staff'),
        ),
        migrations.AddField(
            model_name='staffawardhonour',
            name='staff',
            field=models.ManyToManyField(blank=True, related_name='award_list', to='staffs.staff'),
        ),
        migrations.AddField(
            model_name='staffseminar',
            name='staff',
            field=models.ManyToManyField(blank=True, related_name='seminar_list', to='staffs.staff'),
        ),
    ]
