# Generated by Django 5.1.7 on 2026-07-09 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0037_remove_bookpublication_associated_staffs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffpastdesignation',
            name='approval_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='staffqualification',
            name='approval_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
