# Generated by Django 5.1.7 on 2026-07-09 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0038_staffpastdesignation_approval_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='additional_designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
