# Generated by Django 5.1.7 on 2026-07-13 18:00

import ssm.upload_paths
import ssm.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0039_staff_additional_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffseminar',
            name='mode',
            field=models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline')], default='Offline', max_length=20),
        ),
        migrations.AddField(
            model_name='staffseminar',
            name='order_certificate',
            field=models.FileField(blank=True, help_text='Upload Deputation Order Copy (Optional)', null=True, upload_to=ssm.upload_paths.staff_seminar_order_path, validators=[ssm.validators.validate_file_size]),
        ),
        migrations.AddField(
            model_name='staffseminar',
            name='organized_by',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='staffseminar',
            name='participation_role',
            field=models.CharField(choices=[('Attended', 'Attended'), ('Conducted', 'Conducted')], default='Attended', max_length=20),
        ),
        migrations.AddField(
            model_name='staffseminar',
            name='total_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staffseminar',
            name='event_type',
            field=models.CharField(choices=[('Seminar', 'Seminar'), ('Workshop', 'Workshop'), ('Conference', 'Conference'), ('FDP', 'FDP'), ('Summer/Winter Orientation', 'Summer/Winter Orientation'), ('STTP', 'STTP')], default='Seminar', max_length=40),
        ),
        migrations.AlterField(
            model_name='staffseminar',
            name='supporting_document',
            field=models.FileField(blank=True, help_text='Upload Completion Certificate (Required)', null=True, upload_to=ssm.upload_paths.staff_seminar_document_path, validators=[ssm.validators.validate_file_size]),
        ),
    ]
