# Generated by Django 5.1.7 on 2026-07-13 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0040_staffseminar_mode_staffseminar_order_certificate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalpublication',
            name='is_sci',
            field=models.BooleanField(default=False, verbose_name='SCI'),
        ),
        migrations.AddField(
            model_name='journalpublication',
            name='is_scie',
            field=models.BooleanField(default=False, verbose_name='SCIE'),
        ),
        migrations.AddField(
            model_name='journalpublication',
            name='is_scopus',
            field=models.BooleanField(default=False, verbose_name='SCOPUS'),
        ),
        migrations.AddField(
            model_name='journalpublication',
            name='is_ugc',
            field=models.BooleanField(default=False, verbose_name='UGC'),
        ),
        migrations.AddField(
            model_name='journalpublication',
            name='is_wos',
            field=models.BooleanField(default=False, verbose_name='WOS'),
        ),
    ]
