# Generated by Django 5.1.7 on 2026-07-15 01:54

import ssm.upload_paths
import ssm.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0041_journalpublication_is_sci_journalpublication_is_scie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='appointment_order',
            field=models.FileField(blank=True, null=True, upload_to=ssm.upload_paths.staff_appointment_order_path, validators=[ssm.validators.validate_file_size]),
        ),
        migrations.AddField(
            model_name='staff',
            name='board_order',
            field=models.FileField(blank=True, null=True, upload_to=ssm.upload_paths.staff_board_order_path, validators=[ssm.validators.validate_file_size]),
        ),
        migrations.AddField(
            model_name='staff',
            name='joining_letter',
            field=models.FileField(blank=True, null=True, upload_to=ssm.upload_paths.staff_joining_letter_path, validators=[ssm.validators.validate_file_size]),
        ),
        migrations.AddField(
            model_name='staff',
            name='joining_order',
            field=models.FileField(blank=True, null=True, upload_to=ssm.upload_paths.staff_joining_order_path, validators=[ssm.validators.validate_file_size]),
        ),
    ]
