# Generated by Django 5.1.7 on 2026-07-15 02:07

import ssm.upload_paths
import ssm.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0042_staff_appointment_order_staff_board_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='hsc_marksheet',
            field=models.FileField(blank=True, null=True, upload_to=ssm.upload_paths.staff_hsc_marksheet_path, validators=[ssm.validators.validate_file_size]),
        ),
        migrations.AddField(
            model_name='staff',
            name='sslc_marksheet',
            field=models.FileField(blank=True, null=True, upload_to=ssm.upload_paths.staff_sslc_marksheet_path, validators=[ssm.validators.validate_file_size]),
        ),
    ]
