# Generated by Django 5.1.7 on 2026-07-15 03:14

import ssm.upload_paths
import ssm.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0043_staff_hsc_marksheet_staff_sslc_marksheet'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffPatent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Title of Invention')),
                ('application_number', models.CharField(blank=True, max_length=100, verbose_name='Application Number')),
                ('patent_type', models.CharField(choices=[('Indian', 'Indian'), ('International', 'International')], default='Indian', max_length=20, verbose_name='Patent Type')),
                ('status', models.CharField(choices=[('Applied', 'Applied'), ('Published', 'Published'), ('Granted', 'Granted')], default='Applied', max_length=20, verbose_name='Status')),
                ('application_year', models.CharField(blank=True, max_length=10, verbose_name='Year of Application')),
                ('grant_year', models.CharField(blank=True, max_length=10, verbose_name='Year of Grant (if Granted)')),
                ('inventors', models.CharField(blank=True, max_length=500, verbose_name='Inventor Names (auto-generated)')),
                ('funding_agency', models.CharField(blank=True, max_length=255, verbose_name='Funding Agency (if any)')),
                ('description', models.TextField(blank=True, verbose_name='Brief Description')),
                ('supporting_document', models.FileField(blank=True, help_text='Upload Patent Certificate / Filing Receipt (Max 100KB)', null=True, upload_to=ssm.upload_paths.staff_patent_document_path, validators=[ssm.validators.validate_file_size])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ManyToManyField(blank=True, related_name='patents', to='staffs.staff')),
            ],
            options={
                'ordering': ['-application_year', '-created_at'],
            },
        ),
    ]
