# Generated by Django 5.1.7 on 2026-07-16 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0044_add_staff_patent'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='is_admin',
            field=models.BooleanField(default=False, help_text='Designates whether this staff member has administrative access.', verbose_name='Is Admin'),
        ),
    ]
