# Generated by Django 5.1.7 on 2026-07-16 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0045_staff_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='designation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='staff',
            name='qualification',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='staff',
            name='salutation',
            field=models.CharField(blank=True, choices=[('Dr.', 'Dr.'), ('Prof.', 'Prof.'), ('Mr.', 'Mr.'), ('Ms.', 'Ms.')], max_length=10),
        ),
        migrations.AlterField(
            model_name='staff',
            name='specialization',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
