# Generated by Django 5.1.7 on 2026-07-17 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0046_alter_staff_designation_alter_staff_qualification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_additional_admins', models.PositiveIntegerField(default=3, help_text='The maximum number of staff members (excluding the HOD) that can be set as Admin (is_admin=True).', verbose_name='Max Additional Admins')),
            ],
            options={
                'verbose_name': 'Admin Settings',
                'verbose_name_plural': 'Admin Settings',
            },
        ),
    ]
