# Generated by Django 5.1.7 on 2026-07-17 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0047_adminsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Lab Name')),
                ('code', models.CharField(help_text='Unique identifier for the lab (e.g. IT-LAB-01)', max_length=50, unique=True, verbose_name='Lab Code')),
                ('staff', models.ForeignKey(blank=True, help_text='The staff member in charge of this lab.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_labs', to='staffs.staff', verbose_name='Lab Incharge')),
            ],
            options={
                'verbose_name': 'Lab',
                'verbose_name_plural': 'Labs',
                'ordering': ['name'],
            },
        ),
    ]
