# Generated by Django 5.1.7 on 2026-07-22 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0049_rename_code_to_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='is_scholarship_officer',
            field=models.BooleanField(default=False, help_text='Designates whether this staff member is a scholarship officer.', verbose_name='Scholarship Officer'),
        ),
        migrations.AddField(
            model_name='staff',
            name='is_timetable_incharge',
            field=models.BooleanField(default=False, help_text='Designates whether this staff member is a timetable incharge.', verbose_name='Timetable Incharge'),
        ),
    ]
