# Generated by Django 5.1.7 on 2026-07-23 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0050_staff_is_scholarship_officer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffqualification',
            name='specialization',
            field=models.CharField(blank=True, help_text='Specialization (e.g. Computer Science)', max_length=255, null=True),
        ),
    ]
