# Generated by Django 5.1.7 on 2026-07-25 15:23

import ssm.upload_paths
import ssm.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0051_staffqualification_specialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffstudentguided',
            name='department',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='staffstudentguided',
            name='papers_pdf',
            field=models.FileField(blank=True, help_text='Upload Publication Papers PDF', null=True, upload_to=ssm.upload_paths.staff_student_guided_papers_path, validators=[ssm.validators.validate_file_size]),
        ),
        migrations.AddField(
            model_name='staffstudentguided',
            name='roll_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='staffstudentguided',
            name='thesis_document',
            field=models.FileField(blank=True, help_text='Upload Thesis PDF', null=True, upload_to=ssm.upload_paths.staff_student_guided_thesis_path, validators=[ssm.validators.validate_file_size]),
        ),
        migrations.AddField(
            model_name='staffstudentguided',
            name='thesis_title',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
