# Generated by Django 5.1.7 on 2026-07-26 17:09

import django.db.models.deletion
import ssm.upload_paths
import ssm.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0052_staffstudentguided_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffResearchProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('description', models.TextField(blank=True, default='')),
                ('funded_by', models.CharField(blank=True, default='', max_length=255)),
                ('funding_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Funding amount in INR', max_digits=12, null=True)),
                ('supporting_document', models.FileField(blank=True, help_text='Upload Project Sanction Order or related supporting document (PDF)', null=True, upload_to=ssm.upload_paths.staff_research_project_path, validators=[ssm.validators.validate_file_size])),
                ('status', models.CharField(choices=[('Ongoing', 'Ongoing'), ('Completed', 'Completed')], default='Ongoing', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_projects', to='staffs.staff')),
            ],
            options={
                'ordering': ['-order', '-start_date', 'title'],
            },
        ),
    ]
