# Generated by Django 5.1.7 on 2026-07-26 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0053_staffresearchproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffstudentguided',
            name='viva_date',
            field=models.DateField(blank=True, help_text='Viva Voce Examination Date (Completed Ph.D. scholars)', null=True),
        ),
    ]
