# Generated by Django 5.1.7 on 2026-07-28 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0054_staffstudentguided_viva_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffpastdesignation',
            name='is_additional',
            field=models.BooleanField(default=False),
        ),
    ]
