# Generated by Django 5.1.7 on 2026-07-29 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0055_staffpastdesignation_is_additional'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='assigned_batch',
            field=models.CharField(choices=[('A', 'Batch A'), ('B', 'Batch B'), ('Both', 'Both')], default='Both', help_text='Designate if this course assignment applies to Batch A, Batch B, or Both.', max_length=10),
        ),
    ]
