# Generated by Django 5.1.7 on 2026-07-29 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0056_subject_assigned_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='staff_batch_b',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects_b', to='staffs.staff'),
        ),
    ]
