# Generated by Django 5.1.7 on 2026-08-02 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0057_subject_staff_batch_b'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffstudentguided',
            name='specialization',
            field=models.CharField(blank=True, default='', help_text='Specialization / Area of Research', max_length=255),
        ),
    ]
