# Generated by Django 5.1.7 on 2026-08-02 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0058_staffstudentguided_specialization'),
        ('students', '0051_alter_caste_name_alter_personalinfo_caste_other'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffpatent',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scholar_patents', to='students.student'),
        ),
    ]
