# Generated by Django 5.1.7 on 2026-08-02 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0059_staffpatent_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffseminar',
            options={'ordering': ['-date_from', '-year', '-order', 'title']},
        ),
        migrations.AddField(
            model_name='staffseminar',
            name='national_international',
            field=models.CharField(blank=True, choices=[('National', 'National'), ('International', 'International')], default='National', max_length=30),
        ),
        migrations.AddField(
            model_name='staffseminar',
            name='proceedings_title',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='staffseminar',
            name='sponsoring_agency',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='staffseminar',
            name='event_type',
            field=models.CharField(choices=[('Conference', 'Conference'), ('Seminar', 'Seminar'), ('Workshop', 'Workshop'), ('Symposia', 'Symposia'), ('FDP', 'FDP'), ('STTP', 'STTP'), ('Summer/Winter School', 'Summer/Winter School'), ('Orientation Programme', 'Orientation Programme'), ('Refresher Course / Training', 'Refresher Course / Training')], default='Seminar', max_length=60),
        ),
    ]
