# Generated by Django 5.1.7 on 2026-08-05 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0060_alter_staffseminar_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Indicates whether this timetable entry is published'),
        ),
    ]
