# Generated by Django 5.1.7 on 2026-08-05 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0061_timetable_is_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timetable',
            options={'ordering': ['academic_year', 'semester', 'day', 'period']},
        ),
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='timetable',
            name='academic_year',
            field=models.CharField(default='2026-2027', help_text='Academic year e.g. 2026-2027', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together={('academic_year', 'semester', 'day', 'period', 'batch')},
        ),
    ]
