# Generated by Django 5.1.7 on 2026-08-10 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0062_alter_timetable_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(help_text='e.g. III Year IT - Sem 5', max_length=255, verbose_name='Class Name')),
                ('room_name', models.CharField(help_text='e.g. LH-201, Room 102', max_length=100, verbose_name='Class Room Name')),
                ('semester', models.IntegerField(blank=True, null=True, verbose_name='Semester (1-8)')),
                ('from_date', models.DateField(blank=True, null=True, verbose_name='From Date')),
                ('to_date', models.DateField(blank=True, null=True, verbose_name='To Date')),
                ('staff', models.ForeignKey(blank=True, help_text='The staff member in charge of this class.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_class_mappings', to='staffs.staff', verbose_name='Class Incharge')),
            ],
            options={
                'verbose_name': 'Class Mapping',
                'verbose_name_plural': 'Class Mappings',
                'ordering': ['semester', 'class_name'],
            },
        ),
    ]
