# Generated by Django 5.1.7 on 2026-08-10 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0063_classmapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='staffs.classmapping', verbose_name='Classroom Mapping'),
        ),
        migrations.AddField(
            model_name='subject',
            name='lab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='staffs.lab', verbose_name='Lab Mapping'),
        ),
        migrations.AddField(
            model_name='subject',
            name='location_name',
            field=models.CharField(blank=True, help_text='Assigned class room or lab room name e.g. LH-201, OS Lab', max_length=255, null=True, verbose_name='Location Name'),
        ),
    ]
