# Generated by Django 5.1.7 on 2026-08-10 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0064_subject_classroom_subject_lab_subject_location_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='from_date',
            field=models.DateField(blank=True, help_text='Effective From Date', null=True),
        ),
        migrations.AddField(
            model_name='timetable',
            name='to_date',
            field=models.DateField(blank=True, help_text='Effective To Date', null=True),
        ),
        migrations.CreateModel(
            name='PublishedTimetableVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(default='2026-2027', help_text='Academic year e.g. 2026-2027', max_length=20)),
                ('semester', models.IntegerField(help_text='Semester 1 to 8')),
                ('version_name', models.CharField(default='v1.0', help_text='Timetable Version Name', max_length=100)),
                ('from_date', models.DateField(blank=True, help_text='Effective From Date', null=True)),
                ('to_date', models.DateField(blank=True, help_text='Effective To Date', null=True)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is current active published version')),
                ('timetable_data_json', models.TextField(default='{}', help_text='JSON snapshot of saved timetable grid entries')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staffs.staff')),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
    ]
