# Generated by Django 5.1.7 on 2026-08-10 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0065_timetable_from_date_timetable_to_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishedtimetableversion',
            name='version_name',
            field=models.CharField(blank=True, default='v1.0', help_text='Timetable Version Name', max_length=100, null=True),
        ),
    ]
