# Generated by Django 5.1.7 on 2026-08-10 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0066_alter_publishedtimetableversion_version_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classmapping',
            name='staff',
        ),
    ]
