# Generated by Django 5.1.7 on 2026-08-11 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0067_remove_classmapping_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_number', models.IntegerField(help_text='Task number e.g. 1, 2, 3...', unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='Task / Role Name')),
                ('category', models.CharField(blank=True, default='Department Administration', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_staff', models.ManyToManyField(blank=True, related_name='assigned_department_tasks', to='staffs.staff', verbose_name='Assigned Staff Members')),
            ],
            options={
                'verbose_name': 'Department Task / Role',
                'verbose_name_plural': 'Department Tasks & Roles',
                'ordering': ['task_number'],
            },
        ),
    ]
