# Generated by Django 5.1.7 on 2026-08-18 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0068_departmenttask'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='secondary_roles',
            field=models.CharField(blank=True, help_text="Comma-separated secondary roles (e.g. 'Class Incharge, Scholarship Officer').", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('Teaching Staff', [('HOD', 'HOD'), ('Class Incharge', 'Class Incharge'), ('Course Incharge', 'Course Incharge'), ('Scholarship Officer', 'Scholarship Officer')]), ('Non-Teaching Staff', [('Office Staff', 'Office Staff'), ('Technical Officer', 'Technical Officer')])], default='Course Incharge', max_length=50),
        ),
    ]
