# Generated by Django 5.1.7 on 2026-08-18 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0069_staff_secondary_roles_alter_staff_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('Teaching Staff', [('HOD', 'HOD'), ('Class Incharge', 'Class Incharge'), ('Course Incharge', 'Course Incharge'), ('Scholarship Officer', 'Scholarship Officer'), ('Placement Officer', 'Placement Officer')]), ('Non-Teaching Staff', [('Office Staff', 'Office Staff'), ('Technical Officer', 'Technical Officer')])], default='Course Incharge', max_length=50),
        ),
    ]
