# Generated by Django 5.1.7 on 2026-08-18 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0070_alter_staff_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='assigned_batch',
            field=models.CharField(blank=True, choices=[('All', 'Whole Semester'), ('A', 'Batch A'), ('B', 'Batch B')], default='All', help_text='For Class Incharge: Specify batch assignment (Whole Semester, Batch A, or Batch B).', max_length=10, null=True),
        ),
    ]
