# Generated by Django 5.1.7 on 2026-08-18 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0072_seed_department_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmenttask',
            name='task_number',
            field=models.IntegerField(blank=True, help_text='Task number e.g. 1, 2, 3... (Leave blank to automatically assign the next number)', null=True, unique=True),
        ),
    ]
