# Generated by Django 5.1.7 on 2026-08-19 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0073_alter_departmenttask_task_number'),
        ('students', '0057_scholarshipapplication_supporting_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookpublication',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='scholar_m2m_books', to='students.student'),
        ),
        migrations.AddField(
            model_name='conferenceparticipation',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='scholar_m2m_conferences', to='students.student'),
        ),
        migrations.AddField(
            model_name='journalpublication',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='scholar_m2m_journals', to='students.student'),
        ),
        migrations.AddField(
            model_name='staffpatent',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='scholar_m2m_patents', to='students.student'),
        ),
    ]
