# Generated by Django 5.1.7 on 2026-08-24 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0074_bookpublication_students_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='timetable',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_entries', to='staffs.publishedtimetableversion'),
        ),
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together={('academic_year', 'semester', 'day', 'period', 'batch', 'version')},
        ),
    ]
