# Generated by Django 5.1.7 on 2026-09-02 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0075_alter_timetable_unique_together_timetable_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsubstitutionrequest',
            name='attendance_option',
            field=models.CharField(choices=[('WITH_ATTENDANCE', 'With Attendance (Credited to Temp Staff)'), ('WITHOUT_ATTENDANCE', 'Without Attendance (Credited to Primary Subject Staff)')], default='WITH_ATTENDANCE', help_text='Specifies whether attendance credit goes to temp staff or primary subject staff.', max_length=20),
        ),
    ]
