# Generated by Django 5.1.7 on 2026-09-03 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0076_classsubstitutionrequest_attendance_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookpublication',
            name='author_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='journalpublication',
            name='author_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
