# Generated by Django 5.1.7 on 2026-09-07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0077_alter_bookpublication_author_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='assistant_staff',
            field=models.ForeignKey(
                blank=True,
                help_text='The assistant staff member assigned to this lab.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='assigned_assistant_labs',
                to='staffs.staff',
                verbose_name='Lab Assistant'
            ),
        ),
    ]
