# Generated by Django 5.1.7 on 2026-09-08 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0079_subject_assistant_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='assistant_staff_batch_b',
            field=models.ForeignKey(blank=True, help_text='The assistant staff member assigned for Batch B of this lab subject.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assisted_subjects_b', to='staffs.staff', verbose_name='Lab Assistant Staff (Batch B)'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='assistant_staff',
            field=models.ForeignKey(blank=True, help_text='The assistant staff member assigned to support this lab subject.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assisted_subjects', to='staffs.staff', verbose_name='Lab Assistant Staff (Batch A/Both)'),
        ),
    ]
