# Generated by Django 5.1.7 on 2026-09-08 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0080_subject_assistant_staff_batch_b_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicCalendarOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('day_type', models.CharField(choices=[('Holiday', 'Holiday'), ('WorkingDay', 'Working Day (Day Order)')], default='Holiday', max_length=20)),
                ('day_order', models.CharField(blank=True, choices=[('Monday', 'Monday Order'), ('Tuesday', 'Tuesday Order'), ('Wednesday', 'Wednesday Order'), ('Thursday', 'Thursday Order'), ('Friday', 'Friday Order')], help_text='Effective Day Order for timetable (e.g. Monday Order for a working Saturday)', max_length=20, null=True)),
                ('title', models.CharField(help_text='e.g. Govt Holiday, Working Saturday - Monday Order', max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Academic Calendar Override',
                'verbose_name_plural': 'Academic Calendar Overrides',
                'ordering': ['-date'],
            },
        ),
    ]
