# Generated by Django 5.1.7 on 2026-09-09 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0081_academiccalendaroverride'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffHourSwapRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester_date', models.DateField(help_text="Date of requester's period to give up")),
                ('requester_period', models.IntegerField(help_text="Requester's period (1-7)")),
                ('target_date', models.DateField(help_text="Date of target staff's period to take in exchange")),
                ('target_period', models.IntegerField(help_text="Target staff's period (1-7)")),
                ('reason', models.TextField(blank=True, help_text='Reason for requesting swap', null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('attendance_credit', models.CharField(choices=[('SWAPPED_TEACHER', 'Swapped Staff gets Attendance Credit'), ('PRIMARY_TEACHER', 'Primary Subject Staff retains Credit')], default='SWAPPED_TEACHER', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hour_swaps_requested', to='staffs.staff')),
                ('requester_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_requester_subjects', to='staffs.subject')),
                ('target_staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hour_swaps_received', to='staffs.staff')),
                ('target_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_target_subjects', to='staffs.subject')),
            ],
            options={
                'ordering': ['-requester_date', 'requester_period'],
                'unique_together': {('requester', 'requester_date', 'requester_period')},
            },
        ),
    ]
