# Generated by Django 5.1.7 on 2026-09-09 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0082_staffhourswaprequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('hour_swap', 'Mutual Hour Swap'), ('substitution', 'Class Substitution'), ('leave', 'Leave Request'), ('bonafide', 'Bonafide Certificate'), ('document', 'Document Request'), ('portfolio', 'Portfolio Approval'), ('general', 'General Notification')], default='general', max_length=50)),
                ('url', models.CharField(blank=True, max_length=500, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='staffs.staff')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
