# Generated by Django 5.1.7 on 2026-09-10 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0083_staffnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='assistant_staffs',
            field=models.ManyToManyField(blank=True, help_text='Multiple assistant staff members assigned to support this lab subject.', related_name='assisted_subjects_multi', to='staffs.staff', verbose_name='Lab Assistants (Batch A/Both)'),
        ),
        migrations.AddField(
            model_name='subject',
            name='assistant_staffs_batch_b',
            field=models.ManyToManyField(blank=True, help_text='Multiple assistant staff members assigned for Batch B of this lab subject.', related_name='assisted_subjects_b_multi', to='staffs.staff', verbose_name='Lab Assistants (Batch B)'),
        ),
    ]
