# Generated by Django 5.1.7 on 2026-01-08 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0017_leaverequest_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('Pending Class Incharge', 'Pending Class Incharge'), ('Pending HOD', 'Pending HOD'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending Class Incharge', max_length=30),
        ),
    ]
