# Generated by Django 5.1.7 on 2026-01-08 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0018_alter_leaverequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='rejected_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
