# Generated by Django 5.1.7 on 2026-02-02 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0022_resultscreenshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_password_changed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='is_profile_complete',
            field=models.BooleanField(default=False),
        ),
    ]
