# Generated by Django 5.1.7 on 2026-02-02 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0023_student_is_password_changed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
