# Generated by Django 5.1.7 on 2026-02-02 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0024_alter_student_student_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='plain_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
