# Generated by Django 5.1.7 on 2026-02-02 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0025_student_plain_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='plain_password',
        ),
    ]
