# Generated by Django 5.1.7 on 2026-02-02 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0026_remove_student_plain_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentGenerator',
            fields=[
            ],
            options={
                'verbose_name': 'Generate Students',
                'verbose_name_plural': 'Generate Students',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('students.student',),
        ),
    ]
