# Generated by Django 5.1.7 on 2026-02-03 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0021_news_end_date_news_start_date'),
        ('students', '0027_studentgenerator'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentattendance',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='studentattendance',
            unique_together={('student', 'subject', 'date', 'time')},
        ),
    ]
