# Generated by Django 5.1.7 on 2026-02-03 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0028_alter_studentattendance_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentattendance',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
