# Generated by Django 5.1.7 on 2026-02-06 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0031_studentremark'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='parent_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
