# Generated by Django 5.1.7 on 2026-02-12 17:21

import datetime
import ssm.upload_paths
import ssm.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0035_alter_studentdocuments_aadhaar_card_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentremark',
            name='apology_letter',
            field=models.FileField(blank=True, help_text="Upload student's apology letter", null=True, upload_to='ssm.upload_paths.student_remark_apology_path'),
        ),
        migrations.AddField(
            model_name='studentremark',
            name='custom_violation_text',
            field=models.CharField(blank=True, help_text="Custom violation text when 'Others' is selected", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='studentremark',
            name='evidence_document',
            field=models.FileField(blank=True, help_text='Upload evidence (photo, document, etc.)', null=True, upload_to='ssm.upload_paths.student_remark_evidence_path'),
        ),
        migrations.AddField(
            model_name='studentremark',
            name='incident_date',
            field=models.DateField(default=datetime.datetime(2026, 2, 12, 17, 21, 8, 175482, tzinfo=datetime.timezone.utc), help_text='Date when the incident occurred'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='document',
            field=models.FileField(blank=True, help_text='Required for Medical and OD', null=True, upload_to=ssm.upload_paths.student_leave_document_path),
        ),
        migrations.AlterField(
            model_name='resultscreenshot',
            name='screenshot',
            field=models.ImageField(upload_to=ssm.upload_paths.result_screenshot_path),
        ),
        migrations.AlterField(
            model_name='studentdocuments',
            name='aadhaar_card',
            field=models.FileField(blank=True, null=True, upload_to=ssm.upload_paths.aadhaar_card_path, validators=[ssm.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='studentdocuments',
            name='bank_passbook',
            field=models.FileField(blank=True, null=True, upload_to=ssm.upload_paths.bank_passbook_path, validators=[ssm.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='studentdocuments',
            name='community_certificate',
            field=models.FileField(blank=True, null=True, upload_to=ssm.upload_paths.community_certificate_path, validators=[ssm.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='studentdocuments',
            name='driving_license',
            field=models.FileField(blank=True, null=True, upload_to=ssm.upload_paths.driving_license_path, validators=[ssm.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='studentdocuments',
            name='first_graduate_certificate',
            field=models.FileField(blank=True, null=True, upload_to=ssm.upload_paths.first_graduate_certificate_path, validators=[ssm.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='studentdocuments',
            name='hsc_marksheet',
            field=models.FileField(blank=True, null=True, upload_to=ssm.upload_paths.hsc_marksheet_path, validators=[ssm.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='studentdocuments',
            name='income_certificate',
            field=models.FileField(blank=True, null=True, upload_to=ssm.upload_paths.income_certificate_path, validators=[ssm.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='studentdocuments',
            name='sslc_marksheet',
            field=models.FileField(blank=True, null=True, upload_to=ssm.upload_paths.sslc_marksheet_path, validators=[ssm.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='studentdocuments',
            name='student_id_card',
            field=models.FileField(blank=True, null=True, upload_to=ssm.upload_paths.student_id_card_path, validators=[ssm.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='studentdocuments',
            name='student_photo',
            field=models.ImageField(blank=True, null=True, upload_to=ssm.upload_paths.student_photo_path, validators=[ssm.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='studentremark',
            name='description',
            field=models.TextField(blank=True, help_text='Additional notes or details about the incident', null=True),
        ),
        migrations.AlterField(
            model_name='studentremark',
            name='remark_type',
            field=models.CharField(choices=[('DRESSING_CODE', 'Dressing Code'), ('HAIRCUT_STYLING', 'Haircut / Styling'), ('BEARD', 'Beard'), ('CELL_PHONE', 'Cell Phone'), ('BRACELET', 'Bracelet'), ('MISBEHAVIOR', 'Misbehavior'), ('DRUG_USAGE', 'Drug Usage'), ('ACCIDENT', 'Accident'), ('FIGHTING_QUARREL', 'Fighting / Quarrel'), ('BIKE_RACING', 'Bike Racing'), ('EARRING', 'Earring'), ('OTHER_DEPT_ISSUES', 'Other Department Issues'), ('HOSTEL', 'Hostel'), ('TEASING', 'Teasing'), ('MALPRACTICE', 'Malpractice'), ('THEFT', 'Theft'), ('OTHERS', 'Others')], max_length=50),
        ),
    ]
