# Generated by Django 5.1.7 on 2026-03-25 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0036_studentremark_apology_letter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='lab_batch',
            field=models.CharField(blank=True, choices=[('A', 'Batch A'), ('B', 'Batch B')], max_length=1, null=True),
        ),
    ]
