# Generated by Django 5.1.7 on 2026-04-19 05:16

import django.db.models.deletion
import ssm.upload_paths
import ssm.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0034_alter_staff_email'),
        ('students', '0037_student_lab_batch'),
    ]

    operations = [
        migrations.CreateModel(
            name='RACMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_type', models.CharField(choices=[('Internal', 'Intra Department'), ('External', 'Inter Department')], max_length=20)),
                ('external_name', models.CharField(blank=True, max_length=255)),
                ('external_designation', models.CharField(blank=True, max_length=255)),
                ('external_department', models.CharField(blank=True, max_length=255)),
                ('scholar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rac_members', to='students.student')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rac_memberships', to='staffs.staff')),
            ],
        ),
        migrations.CreateModel(
            name='RCWReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('progress', models.TextField()),
                ('document', models.FileField(blank=True, null=True, upload_to=ssm.upload_paths.scholar_rcw_document_path, validators=[ssm.validators.validate_file_size])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scholar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rcw_reviews', to='students.student')),
            ],
            options={
                'ordering': ['date', 'time'],
            },
        ),
        migrations.CreateModel(
            name='ResearchScholarProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scholar_type', models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time Internal', 'Part Time Internal'), ('Part Time External', 'Part Time External')], max_length=50)),
                ('admission_date', models.DateField()),
                ('admission_order_doc', models.FileField(blank=True, null=True, upload_to=ssm.upload_paths.scholar_admission_doc_path, validators=[ssm.validators.validate_file_size])),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scholar_profile', to='students.student')),
                ('supervisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_scholars', to='staffs.staff')),
            ],
        ),
        migrations.CreateModel(
            name='ZerothReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tentative_title', models.CharField(blank=True, max_length=500)),
                ('rcw001_subject', models.CharField(blank=True, max_length=255)),
                ('rcw002_subject', models.CharField(blank=True, max_length=255)),
                ('rcw003_subject', models.CharField(blank=True, max_length=255)),
                ('rcw004_subject', models.CharField(blank=True, max_length=255)),
                ('exam1_marksheet', models.FileField(blank=True, help_text='Upload marksheet for RCW001 and RCW002', null=True, upload_to=ssm.upload_paths.scholar_zeroth_review_exam1_path, validators=[ssm.validators.validate_file_size])),
                ('exam2_marksheet', models.FileField(blank=True, help_text='Upload marksheet for RCW003 and RCW004', null=True, upload_to=ssm.upload_paths.scholar_zeroth_review_exam2_path, validators=[ssm.validators.validate_file_size])),
                ('scholar', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='zeroth_review', to='students.student')),
            ],
        ),
    ]
