# Generated by Django 5.1.7 on 2026-04-20 16:58

import ssm.upload_paths
import ssm.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0038_racmember_rcwreview_researchscholarprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='is_hosteler',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scholarshipinfo',
            name='is_7_5_reservation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentdocuments',
            name='hostel_fee_challan',
            field=models.FileField(blank=True, null=True, upload_to=ssm.upload_paths.hostel_fee_challan_path, validators=[ssm.validators.validate_file_size]),
        ),
        migrations.AddField(
            model_name='studentdocuments',
            name='tuition_fee_challan',
            field=models.FileField(blank=True, null=True, upload_to=ssm.upload_paths.tuition_fee_challan_path, validators=[ssm.validators.validate_file_size]),
        ),
    ]
