# Generated by Django 5.1.7 on 2026-04-20 17:18

import django.db.models.deletion
import ssm.upload_paths
import ssm.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0039_personalinfo_is_hosteler_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdocuments',
            name='hostel_fee_challan',
        ),
        migrations.RemoveField(
            model_name='studentdocuments',
            name='tuition_fee_challan',
        ),
        migrations.CreateModel(
            name='FeeChallanRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.IntegerField(choices=[(1, 'Year 1'), (2, 'Year 2'), (3, 'Year 3'), (4, 'Year 4'), (5, 'Year 5')])),
                ('is_hosteler', models.BooleanField(default=False)),
                ('tuition_fee_challan', models.FileField(blank=True, null=True, upload_to=ssm.upload_paths.tuition_fee_challan_path, validators=[ssm.validators.validate_file_size])),
                ('hostel_fee_challan', models.FileField(blank=True, null=True, upload_to=ssm.upload_paths.hostel_fee_challan_path, validators=[ssm.validators.validate_file_size])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_challans', to='students.student')),
            ],
            options={
                'ordering': ['student', 'academic_year'],
                'unique_together': {('student', 'academic_year')},
            },
        ),
    ]
