# Generated by Django 5.1.7 on 2026-04-20 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0040_remove_studentdocuments_hostel_fee_challan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feechallanrecord',
            name='academic_year',
            field=models.IntegerField(choices=[(1, 'Year 1'), (2, 'Year 2'), (3, 'Year 3'), (4, 'Year 4')]),
        ),
    ]
