# Generated by Django 5.1.7 on 2026-04-20 17:55

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0041_alter_feechallanrecord_academic_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScholarAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('time_marked', models.TimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('scholar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scholar_attendance', to='students.student')),
            ],
            options={
                'ordering': ['-date', '-time_marked'],
                'unique_together': {('scholar', 'date')},
            },
        ),
    ]
