# Generated by Django 5.1.7 on 2026-04-20 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0042_scholarattendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('Pending Class Incharge', 'Pending Class Incharge'), ('Pending HOD', 'Pending HOD'), ('Pending Guide', 'Pending Guide'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending Class Incharge', max_length=30),
        ),
    ]
