# Generated by Django 5.1.7 on 2026-04-21 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0043_add_pending_guide_leave_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchscholarprofile',
            name='completion_year',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='researchscholarprofile',
            name='status',
            field=models.CharField(choices=[('Ongoing', 'Ongoing'), ('Completed', 'Completed')], default='Ongoing', max_length=20),
        ),
    ]
