# Generated by Django 5.1.7 on 2026-07-13 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0044_researchscholarprofile_completion_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('A1+', 'A1+'), ('A1-', 'A1-'), ('A2+', 'A2+'), ('A2-', 'A2-'), ('A1B+', 'A1B+'), ('A1B-', 'A1B-'), ('A2B+', 'A2B+'), ('A2B-', 'A2B-')], max_length=5),
        ),
    ]
