# Generated by Django 5.1.7 on 2026-07-14 01:34

import django.db.models.deletion
import ssm.validators
import students.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0045_alter_personalinfo_blood_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='rcwreview',
            name='is_final',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PhDProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_stage', models.CharField(choices=[('RAC_REVIEW', 'RAC Review'), ('PRE_SUBMISSION', 'Pre-Submission'), ('SYNOPSIS', 'Synopsis'), ('THESIS_SUBMISSION', 'Thesis Submission'), ('THESIS_HARDBOUND', 'Thesis Hardbound'), ('VIVA_VOCE', 'Viva Voce'), ('MEMO', 'Memo'), ('PROVISIONAL', 'Provisional'), ('DEGREE', 'Degree'), ('COMPLETED', 'Completed')], default='RAC_REVIEW', max_length=50)),
                ('rac_completed_at', models.DateTimeField(blank=True, null=True)),
                ('pre_submission_started_at', models.DateTimeField(blank=True, null=True)),
                ('pre_submission_completed_at', models.DateTimeField(blank=True, null=True)),
                ('synopsis_started_at', models.DateTimeField(blank=True, null=True)),
                ('synopsis_completed_at', models.DateTimeField(blank=True, null=True)),
                ('thesis_started_at', models.DateTimeField(blank=True, null=True)),
                ('thesis_completed_at', models.DateTimeField(blank=True, null=True)),
                ('thesis_hardbound_started_at', models.DateTimeField(blank=True, null=True)),
                ('thesis_hardbound_completed_at', models.DateTimeField(blank=True, null=True)),
                ('viva_voce_started_at', models.DateTimeField(blank=True, null=True)),
                ('viva_voce_completed_at', models.DateTimeField(blank=True, null=True)),
                ('memo_started_at', models.DateTimeField(blank=True, null=True)),
                ('memo_completed_at', models.DateTimeField(blank=True, null=True)),
                ('provisional_started_at', models.DateTimeField(blank=True, null=True)),
                ('provisional_completed_at', models.DateTimeField(blank=True, null=True)),
                ('degree_started_at', models.DateTimeField(blank=True, null=True)),
                ('degree_completed_at', models.DateTimeField(blank=True, null=True)),
                ('pre_sub_letter', models.FileField(blank=True, null=True, upload_to=students.models.phd_progress_doc_path, validators=[ssm.validators.validate_file_size])),
                ('pre_sub_attendance', models.FileField(blank=True, null=True, upload_to=students.models.phd_progress_doc_path, validators=[ssm.validators.validate_file_size])),
                ('pre_sub_circular', models.FileField(blank=True, null=True, upload_to=students.models.phd_progress_doc_path, validators=[ssm.validators.validate_file_size])),
                ('synopsis_letter_copies', models.FileField(blank=True, null=True, upload_to=students.models.phd_progress_doc_path, validators=[ssm.validators.validate_file_size])),
                ('synopsis_copy', models.FileField(blank=True, null=True, upload_to=students.models.phd_progress_doc_path, validators=[ssm.validators.validate_file_size])),
                ('synopsis_panel_of_examiner', models.FileField(blank=True, null=True, upload_to=students.models.phd_progress_doc_path, validators=[ssm.validators.validate_file_size])),
                ('synopsis_foreign_examiner', models.FileField(blank=True, null=True, upload_to=students.models.phd_progress_doc_path, validators=[ssm.validators.validate_file_size])),
                ('synopsis_indian_examiner', models.FileField(blank=True, null=True, upload_to=students.models.phd_progress_doc_path, validators=[ssm.validators.validate_file_size])),
                ('thesis_letter_docs', models.FileField(blank=True, null=True, upload_to=students.models.phd_progress_doc_path, validators=[ssm.validators.validate_file_size])),
                ('thesis_copy_file', models.FileField(blank=True, null=True, upload_to=students.models.phd_progress_doc_path, validators=[ssm.validators.validate_file_size])),
                ('thesis_plagiarism_docs', models.FileField(blank=True, null=True, upload_to=students.models.phd_progress_doc_path, validators=[ssm.validators.validate_file_size])),
                ('hardbound_letters_with_corrections', models.FileField(blank=True, null=True, upload_to=students.models.phd_progress_doc_path, validators=[ssm.validators.validate_file_size])),
                ('hardbound_final_thesis', models.FileField(blank=True, null=True, upload_to=students.models.phd_progress_doc_path, validators=[ssm.validators.validate_file_size])),
                ('hardbound_examiner_report', models.FileField(blank=True, null=True, upload_to=students.models.phd_progress_doc_path, validators=[ssm.validators.validate_file_size])),
                ('viva_date', models.DateField(blank=True, null=True)),
                ('viva_time', models.TimeField(blank=True, null=True)),
                ('viva_fixation', models.FileField(blank=True, null=True, upload_to=students.models.phd_progress_doc_path, validators=[ssm.validators.validate_file_size])),
                ('viva_student_order', models.FileField(blank=True, null=True, upload_to=students.models.phd_progress_doc_path, validators=[ssm.validators.validate_file_size])),
                ('viva_internal_order', models.FileField(blank=True, null=True, upload_to=students.models.phd_progress_doc_path, validators=[ssm.validators.validate_file_size])),
                ('viva_external_order', models.FileField(blank=True, null=True, upload_to=students.models.phd_progress_doc_path, validators=[ssm.validators.validate_file_size])),
                ('viva_circular', models.FileField(blank=True, null=True, upload_to=students.models.phd_progress_doc_path, validators=[ssm.validators.validate_file_size])),
                ('viva_letter_attendance', models.FileField(blank=True, null=True, upload_to=students.models.phd_progress_doc_path, validators=[ssm.validators.validate_file_size])),
                ('memo_copy', models.FileField(blank=True, null=True, upload_to=students.models.phd_progress_doc_path, validators=[ssm.validators.validate_file_size])),
                ('provisional_challan', models.FileField(blank=True, null=True, upload_to=students.models.phd_progress_doc_path, validators=[ssm.validators.validate_file_size])),
                ('provisional_doc', models.FileField(blank=True, null=True, upload_to=students.models.phd_progress_doc_path, validators=[ssm.validators.validate_file_size])),
                ('degree_challan', models.FileField(blank=True, null=True, upload_to=students.models.phd_progress_doc_path, validators=[ssm.validators.validate_file_size])),
                ('degree_doc', models.FileField(blank=True, null=True, upload_to=students.models.phd_progress_doc_path, validators=[ssm.validators.validate_file_size])),
                ('scholar', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='phd_progress', to='students.student')),
            ],
        ),
    ]
