# Generated by Django 5.1.7 on 2026-07-14 02:34

import ssm.upload_paths
import ssm.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0046_rcwreview_is_final_phdprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='academichistory',
            name='hsc_board',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='academichistory',
            name='sslc_board',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='pgdetails',
            name='pg_college_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pgdetails',
            name='pg_college_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='studentdocuments',
            name='pg_marksheet',
            field=models.FileField(blank=True, null=True, upload_to=ssm.upload_paths.pg_marksheet_path, validators=[ssm.validators.validate_file_size]),
        ),
        migrations.AddField(
            model_name='studentdocuments',
            name='ug_marksheet',
            field=models.FileField(blank=True, null=True, upload_to=ssm.upload_paths.ug_marksheet_path, validators=[ssm.validators.validate_file_size]),
        ),
        migrations.AddField(
            model_name='ugdetails',
            name='ug_college_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ugdetails',
            name='ug_college_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
