# Generated by Django 5.1.7 on 2026-07-15 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0047_academichistory_hsc_board_academichistory_sslc_board_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchscholarprofile',
            name='is_visvesvaraya_scheme',
            field=models.BooleanField(default=False),
        ),
    ]
