# Generated by Django 5.1.7 on 2026-07-22 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0048_researchscholarprofile_is_visvesvaraya_scheme'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_class_representative',
            field=models.BooleanField(default=False, verbose_name='Class Representative'),
        ),
    ]
