# Generated by Django 5.1.7 on 2026-07-26 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0049_student_is_class_representative'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caste',
            name='name',
            field=models.CharField(max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='caste_other',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
