# Generated by Django 5.1.7 on 2026-07-26 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0050_alter_caste_name_alter_personalinfo_caste_other'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caste',
            name='name',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='caste_other',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
