# Generated by Django 5.1.7 on 2026-08-10 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0051_alter_caste_name_alter_personalinfo_caste_other'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonafiderequest',
            name='status',
            field=models.CharField(choices=[('Pending Office Approval', 'Pending Office Approval'), ('Approved by HOD', 'Approved by HOD'), ('Waiting for HOD Sign', 'Waiting for HOD Sign'), ('Signed', 'Signed'), ('Ready for Collection', 'Ready for Collection'), ('Collected', 'Collected'), ('Unclaimed', 'Unclaimed / Not Collected'), ('Rejected', 'Rejected')], default='Pending Office Approval', max_length=30),
        ),
    ]
