# Generated by Django 5.1.7 on 2026-08-17 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0052_alter_bonafiderequest_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('10th Marksheet', '10th Marksheet (SSLC)'), ('12th Marksheet', '12th Marksheet (HSC)'), ('Transfer Certificate', 'Transfer Certificate (TC)'), ('Diploma Certificate', 'Diploma Certificate'), ('Community Certificate', 'Community Certificate'), ('Other Certificate', 'Other Original Certificate')], max_length=50)),
                ('reason', models.TextField()),
                ('expected_return_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending Office Review'), ('Ready for Collection', 'Ready for Collection'), ('Collected (Not Returned)', 'Collected / Borrowed (Not Returned)'), ('Returned', 'Returned (Completed)'), ('Rejected', 'Rejected')], default='Pending', max_length=35)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('office_remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ready_at', models.DateTimeField(blank=True, null=True)),
                ('collected_at', models.DateTimeField(blank=True, null=True)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_requests', to='students.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
