# Generated by Django 5.1.7 on 2026-08-17 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0053_documentrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScholarshipApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scholarship_type', models.CharField(choices=[('FG', 'First Graduate Scholarship'), ('BCMBC', 'BC / MBC Welfare Scholarship'), ('POSTMATRIC', 'Post-Matric Scholarship (SC / ST / SCC)'), ('PM', 'Prime Minister (PM) Central Scholarship'), ('GOVT_7_5', 'Govt 7.5% School Reservation Scheme'), ('PUDHUMAI', 'Pudhumai Penn Scheme (Higher Ed for Girls)'), ('TAMIZH', 'Tamizh Puthalvan Scheme'), ('PRIVATE', 'Private / Endowment Scholarship')], max_length=30)),
                ('private_scholarship_name', models.CharField(blank=True, max_length=150)),
                ('application_no', models.CharField(blank=True, help_text='Portal application/registration ref number', max_length=100)),
                ('academic_year', models.CharField(default='2026-2027', max_length=20)),
                ('annual_income', models.PositiveIntegerField(blank=True, help_text='Annual Family Income in INR', null=True)),
                ('income_certificate_no', models.CharField(blank=True, max_length=100)),
                ('bank_account_no', models.CharField(blank=True, max_length=50)),
                ('bank_ifsc', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('Pending Office Review', 'Pending Office Review'), ('Verified & Approved', 'Verified & Approved'), ('Disbursed / Availed', 'Disbursed / Availed'), ('Rejected', 'Rejected')], default='Pending Office Review', max_length=30)),
                ('rejection_reason', models.TextField(blank=True)),
                ('office_remarks', models.TextField(blank=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('disbursed_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scholarship_applications', to='students.student')),
            ],
            options={
                'ordering': ['-applied_at'],
            },
        ),
    ]
