# Generated by Django 5.1.7 on 2026-08-17 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0055_alter_scholarshipapplication_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarshipapplication',
            name='status',
            field=models.CharField(choices=[('Pending Office Verification', 'Pending Office Verification'), ('Verified & Recommended', 'Verified & Recommended'), ('Govt Sanctioned / Amount Received', 'Govt Sanctioned / Amount Received'), ('Not Received / Pending Govt', 'Not Received / Pending Govt'), ('Rejected / Ineligible', 'Rejected / Ineligible')], default='Pending Office Verification', max_length=50),
        ),
    ]
