# Generated by Django 5.1.7 on 2026-08-17 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0056_alter_scholarshipapplication_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarshipapplication',
            name='supporting_document',
            field=models.FileField(blank=True, help_text='Application acknowledgment receipt / income certificate / supporting proof PDF', null=True, upload_to='scholarship_docs/'),
        ),
    ]
