# Generated by Django 5.1.7 on 2026-09-02 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0057_scholarshipapplication_supporting_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='sports_team',
            field=models.CharField(blank=True, choices=[('Team A', 'Team A (Red Dragons)'), ('Team B', 'Team B (Blue Falcons)'), ('Team C', 'Team C (Green Titans)'), ('Team D', 'Team D (Yellow Eagles)')], help_text='Assigned Sports Team for extracurricular activities', max_length=50, null=True),
        ),
    ]
