# Generated by Django 5.1.7 on 2026-09-07 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0077_alter_bookpublication_author_name_and_more'),
        ('students', '0059_club_clubevent_clubattendance_clubmembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='staff_incharge_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incharge_clubs_2', to='staffs.staff'),
        ),
    ]
