# Generated by Django 5.1.7 on 2026-09-08 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0061_clubjoinrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentattendance',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Holiday', 'Holiday'), ('OD', 'On Duty')], default='Present', max_length=20),
        ),
    ]
