# Generated by Django 5.1.7 on 2026-10-05 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0062_alter_studentattendance_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clubjoinrequest',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='clubmembership',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='clubjoinrequest',
            name='academic_year',
            field=models.CharField(default='2025-2026', max_length=20),
        ),
        migrations.AddField(
            model_name='clubmembership',
            name='academic_year',
            field=models.CharField(default='2025-2026', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='clubjoinrequest',
            unique_together={('club', 'student', 'academic_year')},
        ),
        migrations.AlterUniqueTogether(
            name='clubmembership',
            unique_together={('club', 'student', 'academic_year')},
        ),
    ]
