# Generated by Django 5.1.7 on 2026-10-05 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0063_alter_clubjoinrequest_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SportsTeamAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(default='2025-2026', max_length=20)),
                ('sports_team', models.CharField(choices=[('Team A', 'Team A (Red Dragons)'), ('Team B', 'Team B (Blue Falcons)'), ('Team C', 'Team C (Green Titans)'), ('Team D', 'Team D (Yellow Eagles)')], max_length=50)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sports_team_allocations', to='students.student')),
            ],
            options={
                'unique_together': {('student', 'academic_year')},
            },
        ),
    ]
